version: "3.8"

services:
  delayservice:
    image: busybox
    command: >
      sh -c "echo 'Delaying household-management startup for 60 seconds, waiting for database to be ready...'; sleep 60; echo 'Delay complete.'"
  householdmanagement:
    container_name: household_management
    image: ghcr.io/laendleenergy/household_management:latest
    ports:
      - "8082:9000"
    networks:
      - front-tier
      - back-tier
    depends_on:
      householdmanagement-database:
        condition: service_healthy
      delayservice:
        condition: service_completed_successfully
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://householdmanagement-database:5433/quarkus
      - QUARKUS_DATASOURCE_USERNAME=quarkus
      - QUARKUS_DATASOURCE_PASSWORD=quarkus
      - QUARKUS_HTTP_PORT=9000
      - QUARKUS_REDIS_HOSTS=redis://85.215.60.151:6379
  householdmanagement-database:
    container_name: householdmanagement-database
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=quarkus
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - PGUSER=quarkus
      - PGPORT=5433
      - POSTGRES_URL="postgres://quarkus:quarkus@postgres:5433/quarkus"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - back-tier
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "quarkus", "-u", "quarkus"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  front-tier:
    name: householdmanagement-front-tier
  back-tier:
    name: householdmanagement-back-tier